### ISSUE TITLE
Plans to distribute the image via Docker Hub?

### ISSUE THREAD

**Issue by cybrox** [EV21/dynb#4]
Hey, first of all, thanks for writing this script!

I did write something similar a while ago but this seems to be way cleaner and more mature.

Do you have any plans to publish this via Docker Hub directly? It would be a great fit for setting up DynDNS easily via systems that provide the Docker Hub repo out of the box such as a Synology NAS.

Thanks!

**Comment by cybrox** [comment]
Oh, sorry, I checked Docker Hub but it seems I totally missed it 🤦 

Thanks! - I'll set it up with the current version and update to the latest release whenever you get around to push it.

Feel free to close this. - I'm leaving it in case you want it to remain open until you pushed the update.

**Comment by EV21** [comment]
> I checked Docker Hub but it seems I totally missed it 🤦

The docker hub search engine seems to be a complete mess. Unless your project is a more popular one you will never find it unless you know the exact path like [`ev21/dynb`](https://hub.docker.com/search?q=ev21%2Fdynb). When you type 'dyndns client' the result will be all kinds of popular whatever clients but no dyndns at all.
... oh, it looks like they show it at the fifth position when you search for [`dynb`](https://hub.docker.com/search?q=dynb) - It took them some months to get this indexed. Also it looks like the downloads and the star counter have a bigger weight in the ranking algorithm.
