### ISSUE TITLE
DuckDNS update for IPv4 fails because of wrong query field

### ISSUE THREAD

**Issue by Qrrbrbirlbel** [EV21/dynb#5]
As per [DuckDNS specification](https://www.duckdns.org/spec.jsp) the query key für IPv4 is just `&ip=` not `&IPv4=` as it is written in [line 287 of `dynb.sh`](https://github.com/EV21/dynb/blob/main/dynb.sh#L287).

(Unfortunatly, DuckDNS answers with `OK`/`NO CHANGE` when the wrong key is given or only updates IPv6.)

**Comment by EV21** [comment]
Thank you, I will test and merge this in the next days.
